import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import InPageNavigation from "./inPageNavigation";

function MatchDetail() {
  let { id } = useParams();

  let fixedData = {
    matchInfo: {
      matchId: 116615,
      matchDescription: "1st Match",
      matchFormat: "T20",
      matchType: "league",
      complete: true,
      domestic: false,
      matchStartTimestamp: 1755212400000,
      matchCompleteTimestamp: 1755223410977,
      dayNight: false,
      year: 2025,
      state: "complete",
      team1: {
        id: 302,
        name: "St Kitts and Nevis Patriots",
        playerDetails: [
          {
            id: 8579,
            name: "Lewis",
            fullName: "Evin Lewis",
            nickName: "Lewis",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "SNP",
            faceImageId: 244670,
          },
          {
            id: 1394,
            name: "Andre Fletcher",
            fullName: "Andre Fletcher",
            nickName: "Fletcher",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "SNP",
            faceImageId: 146338,
          },
          {
            id: 8440,
            name: "K Mayers",
            fullName: "Kyle Mayers",
            nickName: "Mayers",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm medium",
            teamName: "SNP",
            faceImageId: 244721,
          },
          {
            id: 2244,
            name: "Rossouw",
            fullName: "Rilee Rossouw",
            nickName: "Rossouw",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "SNP",
            faceImageId: 593768,
            isOverseas: true,
          },
          {
            id: 13352,
            name: "Alick Athanaze",
            fullName: "Alick Athanaze",
            nickName: "Athanaze",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "SNP",
            faceImageId: 583422,
          },
          {
            id: 8313,
            name: "Holder",
            fullName: "Jason Holder",
            nickName: "Holder",
            captain: true,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "SNP",
            faceImageId: 601745,
          },
          {
            id: 11211,
            name: "Jyd Goolie",
            fullName: "Jyd Goolie",
            nickName: "Jyd Goolie",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm off break",
            teamName: "SNP",
            faceImageId: 182026,
          },
          {
            id: 15034,
            name: "Abbas Afridi",
            fullName: "Abbas Afridi",
            nickName: "Abbas Afridi",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "SNP",
            faceImageId: 582350,
            isOverseas: true,
          },
          {
            id: 14247,
            name: "Naseem Shah",
            fullName: "Naseem Shah",
            nickName: "Naseem Shah",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast",
            teamName: "SNP",
            faceImageId: 616439,
            isOverseas: true,
          },
          {
            id: 14282,
            name: "Fazalhaq Farooqi",
            fullName: "Fazalhaq Farooqi",
            nickName: "Fazalhaq Farooqi",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "SNP",
            faceImageId: 616558,
            isOverseas: true,
          },
          {
            id: 14277,
            name: "Waqar Salamkheil",
            fullName: "Waqar Salamkheil",
            nickName: "Waqar Salamkheil",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "SNP",
            faceImageId: 182026,
            isOverseas: true,
          },
          {
            id: 1446985,
            name: "Navian Bidaisee",
            fullName: "Navian Bidaisee",
            nickName: "Navian Bidaisee",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "SNP",
            faceImageId: 182026,
          },
          {
            id: 8367,
            name: "Mohammad Nawaz",
            fullName: "Mohammad Nawaz",
            nickName: "Nawaz",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "SNP",
            faceImageId: 352425,
          },
          {
            id: 19761,
            name: "Mikyle Louis",
            fullName: "Mikyle Louis",
            nickName: "Mikyle Louis",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm leg break",
            teamName: "SNP",
            faceImageId: 583419,
          },
          {
            id: 11447,
            name: "Jeremiah Louis",
            fullName: "Jeremiah Louis",
            nickName: "Jeremiah Louis",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "SNP",
            faceImageId: 182026,
          },
          {
            id: 13750,
            name: "Dominic Drakes",
            fullName: "Dominic Drakes",
            nickName: "Drakes",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 302,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "SNP",
            faceImageId: 226329,
          },
          {
            id: 13400,
            name: "Ashmead Nedd",
            fullName: "Ashmead Nedd",
            nickName: "Ashmead Nedd",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "Left arm orthodox",
            teamName: "SNP",
            faceImageId: 157863,
          },
          {
            id: 15062,
            name: "Leniko Boucher",
            fullName: "Leniko Boucher",
            nickName: "Boucher",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 302,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "SNP",
            faceImageId: 182026,
          },
        ],
        shortName: "SNP",
      },
      team2: {
        id: 1978,
        name: "Antigua and Barbuda Falcons",
        playerDetails: [
          {
            id: 9394,
            name: "R Cornwall",
            fullName: "Rahkeem Cornwall",
            nickName: "Cornwall",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "ABF",
            faceImageId: 182026,
          },
          {
            id: 54287,
            name: "Jewel Andrew",
            fullName: "Jewel Andrew",
            nickName: "Jewel Andrew",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "",
            teamName: "ABF",
            faceImageId: 182026,
          },
          {
            id: 52428,
            name: "Bevon Jacobs",
            fullName: "Bevon Jacobs",
            nickName: "Bevon Jacobs",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "ABF",
            faceImageId: 182026,
            isOverseas: true,
          },
          {
            id: 544,
            name: "Shakib",
            fullName: "Shakib Al Hasan",
            nickName: "Shakib",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "ABF",
            faceImageId: 351919,
            isOverseas: true,
          },
          {
            id: 9785,
            name: "Fabian Allen",
            fullName: "Fabian Allen",
            nickName: "Fabian Allen",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Left arm orthodox",
            teamName: "ABF",
            faceImageId: 170794,
          },
          {
            id: 10408,
            name: "Imad Wasim",
            fullName: "Imad Wasim",
            nickName: "Imad Wasim",
            captain: true,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "LEFT",
            bowlingStyle: "Left arm orthodox",
            teamName: "ABF",
            faceImageId: 170782,
            isOverseas: true,
          },
          {
            id: 11215,
            name: "Odean Smith",
            fullName: "Odean Smith",
            nickName: "Odean Smith",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "ABF",
            faceImageId: 244724,
          },
          {
            id: 15817,
            name: "Jayden Seales",
            fullName: "Jayden Seales",
            nickName: "Jayden Seales",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "LEFT",
            bowlingStyle: "Right Arm medium",
            teamName: "ABF",
            faceImageId: 537812,
          },
          {
            id: 36501,
            name: "AM Ghazanfar",
            fullName: "AM Ghazanfar",
            nickName: "AM Ghazanfar",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "ABF",
            faceImageId: 581227,
            isOverseas: true,
          },
          {
            id: 11221,
            name: "Obed McCoy",
            fullName: "Obed McCoy",
            nickName: "Obed McCoy",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "LEFT",
            bowlingStyle: "Left Arm fast medium",
            teamName: "ABF",
            faceImageId: 244723,
          },
          {
            id: 14811,
            name: "Karima Gore",
            fullName: "Karima Gore",
            nickName: "Karima Gore",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Left arm orthodox",
            teamName: "ABF",
            faceImageId: 182026,
            isOverseas: true,
          },
          {
            id: 8433,
            name: "Justin Greaves",
            fullName: "Justin Greaves",
            nickName: "Justin Greaves",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "ABF",
            faceImageId: 583423,
          },
          {
            id: 15810,
            name: "Joshua James",
            fullName: "Joshua James",
            nickName: "Joshua James",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm medium",
            teamName: "ABF",
            faceImageId: 182026,
          },
          {
            id: 11289,
            name: "Naveen-ul-Haq",
            fullName: "Naveen-ul-Haq",
            nickName: "Naveen-ul-Haq",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "ABF",
            faceImageId: 352447,
          },
          {
            id: 24006,
            name: "Kevin Wickham",
            fullName: "Kevin Wickham",
            nickName: "Kevin Wickham",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm off break",
            teamName: "ABF",
            faceImageId: 182026,
          },
          {
            id: 11223,
            name: "Shamar Springer",
            fullName: "Shamar Springer",
            nickName: "Shamar Springer",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 1978,
            battingStyle: "RIGHT",
            bowlingStyle: "Right Arm fast medium",
            teamName: "ABF",
            faceImageId: 157847,
          },
          {
            id: 12674,
            name: "Amir Jangoo",
            fullName: "Amir Jangoo",
            nickName: "Jangoo",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 1978,
            battingStyle: "LEFT",
            bowlingStyle: "",
            teamName: "ABF",
            faceImageId: 182026,
          },
        ],
        shortName: "ABF",
      },
      series: {
        id: 9575,
        name: "Caribbean Premier League 2025",
        seriesType: "",
        startDate: 1755043200000,
        endDate: 1758499200000,
        seriesFolder: "",
        odiSeriesResult: "",
        t20SeriesResult: "''",
        testSeriesResult: "",
        tournament: true,
      },
      umpire1: {
        id: 9541,
        name: "Christopher Taylor",
        country: "WI",
      },
      umpire2: {
        id: 9520,
        name: "Gregory Brathwaite",
        country: "WI",
      },
      umpire3: {
        id: 402,
        name: "Deighton Butler",
        country: "WI",
      },
      referee: {
        id: 4236,
        name: "Reon King",
        country: "WI",
      },
      tossResults: {
        tossWinnerId: 302,
        tossWinnerName: "St Kitts and Nevis Patriots",
        decision: "Bowling",
      },
      result: {
        resultType: "win",
        winningTeam: "St Kitts and Nevis Patriots",
        winningteamId: 302,
        winningMargin: 6,
        winByRuns: false,
        winByInnings: false,
      },
      venue: {
        id: 96,
        name: "Warner Park",
        city: "Basseterre, St Kitts",
        country: "West Indies",
        timezone: "-04:00",
        latitude: "17.298562",
        longitude: "-62.723093",
      },
      status: "St Kitts and Nevis Patriots opt to bowl",
      playersOfTheMatch: [
        {
          id: 14277,
          name: "Waqar Salamkheil",
          fullName: "Waqar Salamkheil",
          nickName: "Waqar Salamkheil",
          captain: false,
          keeper: false,
          substitute: false,
          teamName: "Kandahar Knights",
          faceImageId: 182026,
        },
      ],
      playersOfTheSeries: [],
      revisedTarget: {
        reason: "",
      },
      matchTeamInfo: [
        {
          battingTeamId: 1978,
          battingTeamShortName: "ABF",
          bowlingTeamId: 302,
          bowlingTeamShortName: "SNP",
        },
        {
          battingTeamId: 302,
          battingTeamShortName: "SNP",
          bowlingTeamId: 1978,
          bowlingTeamShortName: "ABF",
        },
      ],
      isMatchNotCovered: false,
      HYSEnabled: 1,
      livestreamEnabled: false,
      isFantasyEnabled: true,
      livestreamEnabledGeo: [
        "MA",
        "VN",
        "KW",
        "ID",
        "EG",
        "SG",
        "TH",
        "MY",
        "TN",
        "MO",
        "TW",
        "PH",
        "JO",
        "MR",
        "US",
        "BH",
        "HK",
        "SD",
        "LY",
        "IR",
        "IQ",
        "SA",
        "MU",
        "MN",
        "SY",
        "CC",
        "AE",
        "LB",
        "DJ",
        "SO",
        "BN",
        "KH",
        "KR",
        "SS",
        "CX",
        "FM",
        "YT",
        "YE",
        "RE",
        "OM",
        "DZ",
        "QA",
        "TL",
        "LA",
        "CA",
        "JP",
        "CN",
        "NC",
        "TD",
        "PS",
      ],
      alertType: "auto",
      shortStatus: "SNP won",
      matchImageId: 737658,
    },
    venueInfo: {
      established: 2006,
      capacity: "8,000 (10,000 incl temporary seating)",
      knownAs: null,
      ends: "Pavillion End, Lozack Road End",
      city: "Basseterre, St Kitts",
      country: "West Indies",
      timezone: "-04:00",
      homeTeam: "Leeward Islands",
      floodlights: false,
      curator: null,
      profile: null,
      imageUrl:
        "http://i.cricketcb.com/i/stats/fth/540x303/venue/images/96.jpg",
      ground: "Warner Park",
      groundLength: 0,
      groundWidth: 0,
      otherSports: null,
    },
    broadcastInfo: [
      {
        country: "IN",
        broadcaster: [
          {
            broadcastType: "Streaming",
            value: "Fancode",
          },
          {
            broadcastType: "TV",
            value: "Star Sports Network",
          },
        ],
      },
    ],
  };

  const [data, setData] = useState([]);

  async function FetchMatchDetail() {
    const url = `https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/${id}`;
    const options = {
      method: "GET",
      headers: {
        "x-rapidapi-key": "ac73a44d96mshc3fc97b091e8259p13a118jsnbf7eeef0fc1f",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
      },
    };

    try {
      const response = await fetch(url, options);
      const result = await response.json();
      console.log(result);
      setData(result);
    } catch (error) {
      console.error(error);
    }
  }

  useEffect(() => {
    // FetchMatchDetail();
  }, []);

  return (
    <div className="w-full p-4">
      <h1 className="text-xl font-bold mb-6 text-center text-gray-100">
        Match Detail
      </h1>

     <InPageNavigation
  teams={[
    fixedData.matchInfo.team1.shortName,
    fixedData.matchInfo.team2.shortName,
  ]}
>
  {/* 🔹 Team 1 Players */}
  <div className="flex flex-col items-center space-y-4 w-full">
    {fixedData.matchInfo.team1.playerDetails.map((data, i) => (
      <div
        key={i}
        className="w-full max-w-2xl bg-gray-900/70 px-5 py-4 rounded-lg border border-gray-700 shadow-md hover:bg-gray-800/80 transition"
      >
        <h2 className="text-lg font-semibold text-gray-100">
          {data.fullName}
        </h2>
        <p className="text-gray-400 text-sm">{data.role}</p>
      </div>
    ))}
  </div>

  {/* 🔹 Team 2 Players */}
  <div className="flex flex-col items-center space-y-4 w-full">
    {fixedData.matchInfo.team2.playerDetails.map((data, i) => (
      <div
        key={i}
        className="w-full max-w-2xl bg-gray-900/70 px-5 py-4 rounded-lg border border-gray-700 shadow-md hover:bg-gray-800/80 transition"
      >
        <h2 className="text-lg font-semibold text-gray-100">
          {data.fullName}
        </h2>
        <p className="text-gray-400 text-sm">{data.role}</p>
      </div>
    ))}
  </div>
</InPageNavigation>
    </div>
  );
}

export default MatchDetail;
